[package]
name = "futures-io"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
homepage = "https://github.com/rust-lang-nursery/futures-rs"
documentation = "https://docs.rs/futures-io"
description = """
The `AsyncRead` and `AsyncWrite` traits for the futures-rs library.
"""

[features]
std = ["futures-core/std", "iovec"]
default = ["std"]

# For building docs only
docs = ["std", "futures-core/docs"]

[dependencies]
futures-core = { path = "../futures-core", version = "0.2.0", default-features = false }
iovec = { version = "0.1", optional = true }

[dev-dependencies]
futures = { path = "../futures", version = "0.2.0" }

[package.metadata.docs.rs]
features = ["docs"]
