[package]
name = "futures-macro-await"
version = "0.2.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-lang-nursery/futures-rs"
description = """
Definition of the `await!` macro for the `futures` crate.
"""

[dev-dependencies]
futures = { path = "../futures" }

[features]
nightly = ["futures/nightly"]

# For building docs only
docs = []

[package.metadata.docs.rs]
features = ["docs"]
